services:
  - type: web
    name: gift-registry-backend
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: SECRET_KEY
        value: 0708
      - key: ADMIN_PASSWORD
        value: 0708 